#!/bin/bash
yum -y install gcc openssl-devel pcre-devel  #装包
tar -xf lnmp_soft.tar.gz #解压
cd lnmp_soft 
tar -xf nginx-1.12.2.tar.gz #解压
cd nginx-1.12.2 
./configure --with-http_ssl_module #编译源码,选用模块
make &&make install  #安装
 yum -y install  mariadb  mariadb-server  mariadb-devel
 yum -y install  php  php-mysql
 yum -y install  php-fpm
systemctl stop httpd
/usr/local/nginx/sbin/nginx
sed -i  65,71s/#// /usr/local/nginx/conf/nginx.conf #使用sed,65到71行去掉开头的#号
sed -i 69s/^/#/ /usr/local/nginx/conf/nginx.conf  #使用sed,69行开头加上#
sed  -i 70s/fastcgi_params/fastcgi.conf/  /usr/local/nginx/conf/nginx.conf #用sed,把70行的fastcgi_parnams换成fastcgi.conf
systemctl start mariadb
systemctl status mariadb
systemctl start  php-fpm
systemctl status php-fpm
/usr/local/nginx/sbin/nginx -s reload   #重启nginx

~                                       
