#!/bin/bash
yum -y install gcc openssl-devel pcre-devel
tar -xf lnmp_soft.tar.gz
cd lnmp_soft
tar -xf nginx-1.12.2.tar.gz
cd nginx-1.12.2
./configure --with-http_ssl_module
make &&make install
 yum -y install  mariadb  mariadb-server  mariadb-devel
 yum -y install  php  php-mysql
 yum -y install  php-fpm
systemctl stop httpd
/usr/local/nginx/sbin/nginx
sed -i  65,71s/#// /usr/local/nginx/conf/nginx.conf
sed -i 69s/^/#/ /usr/local/nginx/conf/nginx.conf
sed  -i 70s/fastcgi_params/fastcgi.conf/  /usr/local/nginx/conf/nginx.conf
systemctl start mariadb
systemctl status mariadb
systemctl start  php-fpm
systemctl status php-fpm
/usr/local/nginx/sbin/nginx -s reload

~                                       
